name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          registry: localhost:5000
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t your-image:latest .
          docker tag your-image:latest localhost:5000/your-image:latest

      - name: Push Docker image to local registry
        run: |
          docker push localhost:5000/your-image:latest

      - name: Deploy with Docker Compose
        run: |
          docker-compose down
          docker-compose up -d
